version: 0.4.0.{build}
skip_non_tags: false
clone_folder: c:\seo-metadata
build_script:
- cmd: >-
    cd c:\seo-metadata


    nuget restore app\Epiphany.SeoMetadata\Epiphany.SeoMetadata.sln


    npm install

    npm install grunt@0.4.5 --save-dev

    npm install -g grunt-cli

    grunt nuget
    
    grunt package
artifacts:
- path: pkg\nuget\*
- path: pkg\umbraco\*
nuget:
  account_feed: true
  project_feed: true
deploy:
- provider: NuGet
  api_key:
    secure: knxgwH5a9amElcEhLWera7bfkrOIO5YFQvDuJ9T7nN93bsbarPSWfaRM05nsu5iE
  artifact: /.*\.nupkg/
  on:
    branch: master
